DATA SEGMENT
	MESS DB 'Hello,World!$'   ;字符串数据
DATA ENDS
CODE SEGMENT
ASSUME CS:CODE,DS:DATA
START:	MOV AX,DATA
	MOV DS,AX
	MOV AL,0
	MOV CX,3
OUTPUT0: OUT 32H,AL
	NOP
	LOOP OUTPUT0        ;写入空指令
	MOV AL,01000000B    ;写入复位命令
	OUT 32H,AL         
	NOP
	MOV AL,01001110B    ;方式字
	OUT 32H,AL
	NOP
	MOV AL,00010101B     ;命令字
	OUT 32H,AL
	NOP
	MOV BX,OFFSET MESS
AGAIN:	IN AL,32H
	TEST AL,01H
	JZ AGAIN
	MOV AL,[BX]
	OUT 30H,AL
	INC BX
	CMP BYTE PTR[BX],'$'
	JNZ AGAIN
	JMP $
CODE ENDS
END START

